# ==============================================================================
# RIDS - First Time Setup
# ==============================================================================
# Run this script ONCE before launching the app for the first time.
# 1. Edit the three paths in section 2
# 2. Run the entire script
# 3. Launch app.R
# ==============================================================================

# 1. Install dependencies ------------------------------------------------------
source("R/dependencies.R")

# 2. Configure paths -----------------------------------------------------------
# Edit these to match your shared network drive or local paths

DB_DIR          <- "//shared-drive/RIDS/data/RIDS.duckdb"
ICT_UPLOAD_DIR  <- "//shared-drive/RIDS/uploads"
EDGE_OUTPUT_DIR <- "//shared-drive/RIDS/outputs"
ADMIN_USERNAME  <- "admin"  # your admin account username

# 3. Write config.R ------------------------------------------------------------
writeLines(
  c(
    "# Auto-generated by SETUP/new_setup.R — do not edit manually",
    "# Re-run SETUP/new_setup.R to update paths",
    paste0('DB_DIR          <- "', DB_DIR,          '"'),
    paste0('ICT_UPLOAD_DIR  <- "', ICT_UPLOAD_DIR,  '"'),
    paste0('EDGE_OUTPUT_DIR <- "', EDGE_OUTPUT_DIR, '"')
  ),
  "config.R"
)
message("✓ config.R written")

# 4. Create directories --------------------------------------------------------
dirs <- c(dirname(DB_DIR), ICT_UPLOAD_DIR, EDGE_OUTPUT_DIR)
for (path in dirs) {
  if (!dir.exists(path)) {
    dir.create(path, recursive = TRUE)
    message("✓ Created directory: ", path)
  } else {
    message("  Directory already exists: ", path)
  }
}

# 5. Initialise database -------------------------------------------------------
library(DBI)
library(duckdb)

CON <- dbConnect(duckdb(), DB_DIR)
message("✓ Connected to DB: ", DB_DIR)

source("R/utils/auth.r")
source("R/setup.r")

# Override bootstrap_admin to use the configured username
bootstrap_admin <- function() {
  count <- dbGetQuery(CON, "SELECT COUNT(*) AS n FROM users")$n
  if (count == 0) {
    message("Bootstrapping admin user: ", ADMIN_USERNAME)
    dbExecute(CON,
              "INSERT INTO users (username, role) VALUES (?, ?)",
              params = list(ADMIN_USERNAME, "admin")
    )
    user_id <- dbGetQuery(CON,
                          "SELECT id FROM users WHERE username = ?",
                          params = list(ADMIN_USERNAME)
    )$id
    token <- generate_token(user_id)
    message("╔══════════════════════════════════════╗")
    message("║  ADMIN SETUP TOKEN (expires 24hrs)   ║")
    message("║  ", token, "  ║")
    message("╚══════════════════════════════════════╝")
  } else {
    message("  Users table already populated — skipping admin bootstrap")
  }
}

db_main()
dbDisconnect(CON, shutdown = TRUE)
message("✓ Database initialised")

# 6. Done ----------------------------------------------------------------------
message("")
message("╔══════════════════════════════════════════════════════╗")
message("║  Setup complete. Use the token above to activate     ║")
message("║  your admin account, then launch app.R               ║")
message("╚══════════════════════════════════════════════════════╝")