deployment_config_candidates <- function(app_dir = getwd()) {
  env_path <- trimws(Sys.getenv("RIDS_CONFIG_PATH", ""))
  candidates <- c()

  if (nzchar(env_path)) {
    candidates <- c(candidates, env_path)
  }

  candidates <- c(
    candidates,
    file.path(app_dir, "deployment", "deployment_config.R"),
    file.path(app_dir, "config.R")
  )

  unique(normalizePath(candidates, winslash = "/", mustWork = FALSE))
}

read_runtime_config <- function(path) {
  cfg_env <- new.env(parent = baseenv())
  sys.source(path, envir = cfg_env)

  get_value <- function(name, default = NULL) {
    if (exists(name, envir = cfg_env, inherits = FALSE)) {
      get(name, envir = cfg_env, inherits = FALSE)
    } else {
      default
    }
  }

  storage_mode <- tolower(trimws(as.character(get_value("STORAGE_MODE", "duckdb"))))
  if (!nzchar(storage_mode)) {
    storage_mode <- "duckdb"
  }

  cfg <- list(
    storage_mode = storage_mode,
    db_dir = as.character(get_value("DB_DIR", "")),
    ict_upload_dir = as.character(get_value("ICT_UPLOAD_DIR", "")),
    edge_output_dir = as.character(get_value("EDGE_OUTPUT_DIR", "")),
    app_host = as.character(get_value("APP_HOST", "127.0.0.1")),
    app_port = suppressWarnings(as.integer(get_value("APP_PORT", 3838L))),
    sql_server = as.character(get_value("SQL_SERVER", "")),
    sql_database = as.character(get_value("SQL_DATABASE", "")),
    sql_driver = as.character(get_value("SQL_DRIVER", "")),
    source_path = normalizePath(path, winslash = "/", mustWork = FALSE)
  )

  if (!nzchar(cfg$db_dir)) {
    stop("The deployment config is missing DB_DIR: ", path)
  }

  if (!nzchar(cfg$ict_upload_dir)) {
    stop("The deployment config is missing ICT_UPLOAD_DIR: ", path)
  }

  if (!nzchar(cfg$edge_output_dir)) {
    stop("The deployment config is missing EDGE_OUTPUT_DIR: ", path)
  }

  if (is.na(cfg$app_port) || cfg$app_port <= 0) {
    cfg$app_port <- 3838L
  }

  cfg
}

load_runtime_config <- function(app_dir = getwd()) {
  candidates <- deployment_config_candidates(app_dir)

  for (candidate in candidates) {
    if (file.exists(candidate)) {
      return(read_runtime_config(candidate))
    }
  }

  stop(
    paste(
      "No deployment config found.",
      "Run R/SETUP/new_setup.R before launching the app.",
      "Looked in:",
      paste(candidates, collapse = ", ")
    )
  )
}

connect_primary_database <- function(config) {
  if (!identical(config$storage_mode, "duckdb")) {
    stop("Only DuckDB is supported in this release. Config requested: ", config$storage_mode)
  }

  dbConnect(duckdb(), config$db_dir)
}

write_deployment_config <- function(path, config) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)

  lines <- c(
    "# Auto-generated by R/SETUP/new_setup.R — do not edit manually",
    "# Re-run R/SETUP/new_setup.R to update these values",
    paste0('STORAGE_MODE   <- "', config$storage_mode, '"'),
    paste0('DB_DIR         <- "', config$db_dir, '"'),
    paste0('ICT_UPLOAD_DIR <- "', config$ict_upload_dir, '"'),
    paste0('EDGE_OUTPUT_DIR <- "', config$edge_output_dir, '"'),
    paste0('APP_HOST       <- "', config$app_host, '"'),
    paste0("APP_PORT       <- ", as.integer(config$app_port)),
    paste0('SQL_SERVER     <- "', config$sql_server, '"'),
    paste0('SQL_DATABASE   <- "', config$sql_database, '"'),
    paste0('SQL_DRIVER     <- "', config$sql_driver, '"')
  )

  writeLines(lines, path, useBytes = TRUE)
  invisible(path)
}

write_launcher_r_script <- function(path, app_dir, config_path, app_host, app_port) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)

  lines <- c(
    "# Auto-generated by R/SETUP/new_setup.R",
    sprintf('app_dir <- "%s"', normalizePath(app_dir, winslash = "/", mustWork = TRUE)),
    sprintf('config_path <- "%s"', normalizePath(config_path, winslash = "/", mustWork = FALSE)),
    sprintf('app_host <- "%s"', app_host),
    sprintf("app_port <- %sL", as.integer(app_port)),
    "",
    "if (!file.exists(file.path(app_dir, 'app.R'))) {",
    "  stop('app.R was not found in the shared app folder: ', app_dir)",
    "}",
    "",
    "if (!file.exists(config_path)) {",
    "  stop('deployment_config.R was not found: ', config_path)",
    "}",
    "",
    "Sys.setenv(RIDS_CONFIG_PATH = config_path)",
    "suppressPackageStartupMessages(library(shiny))",
    "message('Starting RIDS on ', app_host, ':', app_port)",
    "shiny::runApp(appDir = app_dir, host = app_host, port = app_port, launch.browser = FALSE)"
  )

  writeLines(lines, path, useBytes = TRUE)
  invisible(path)
}

write_launcher_bat <- function(path, launcher_r_path, app_port) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)

  lines <- c(
    "@echo off",
    "setlocal",
    "set \"SCRIPT_DIR=%~dp0\"",
    sprintf("set \"LAUNCH_R=%s\"", normalizePath(launcher_r_path, winslash = "\\", mustWork = FALSE)),
    "",
    "if not exist \"%LAUNCH_R%\" (",
    "  echo Launch script not found: %LAUNCH_R%",
    "  pause",
    "  exit /b 1",
    ")",
    "",
    "set \"RSCRIPT_EXE=\"",
    "for %%D in (\"%ProgramFiles%\\R\" \"%ProgramFiles(x86)%\\R\") do (",
    "  if exist \"%%~D\" (",
    "    for /f \"delims=\" %%V in ('dir /b /ad-h /o-n \"%%~D\\R-*\" 2^>nul') do (",
    "      if exist \"%%~D\\%%V\\bin\\Rscript.exe\" (",
    "        set \"RSCRIPT_EXE=%%~D\\%%V\\bin\\Rscript.exe\"",
    "        goto :found_rscript",
    "      )",
    "    )",
    "  )",
    ")",
    "",
    ":found_rscript",
    "if not defined RSCRIPT_EXE (",
    "  echo R was not found on this laptop.",
    "  echo Please install R and try again.",
    "  pause",
    "  exit /b 1",
    ")",
    "",
    "start \"RIDS\" \"%RSCRIPT_EXE%\" \"%LAUNCH_R%\"",
    "timeout /t 5 /nobreak >nul",
    sprintf("start \"\" \"http://127.0.0.1:%s\"", as.integer(app_port)),
    "endlocal"
  )

  writeLines(lines, path, useBytes = TRUE)
  invisible(path)
}
